// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AviAppFinal.Server.Models;
using System;
using System.Collections.Generic;

namespace AviFinal.Api.Models
{
    public partial class Ge35bcinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Ge35bdinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Ge35bsinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Ge35cfinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Ge35clinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Ge35deinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Ge35ecinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Ge35edinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Ge35flinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Ge35mginspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Ge35odinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Ge35rfinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Ge35sninspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }
}
