// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AviAppFinal.Server.Models;
using System;
using System.Collections.Generic;

namespace AviFinal.Api.Models
{
    public partial class Ge36bdinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Ge36cainspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Ge36cfinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Ge36clinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Ge36deinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Ge36ecinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Ge36edinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Ge36flinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Ge36mginspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Ge36rfinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Ge36sninspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }
}
