// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AviFinal.Api.Models;

public partial class GE36SNInspect
{
    public int ID { get; set; }

    public int LocoNumber { get; set; }

    public string LocoClass { get; set; }

    public string LocoModel { get; set; }

    public string FormID { get; set; }

    public string PartID { get; set; }

    public string PartDescr { get; set; }

    public string GoodCheck { get; set; }

    public string RefurbishCheck { get; set; }

    public string MissingCheck { get; set; }

    public string ReplaceCheck { get; set; }

    public string RefurbishValue { get; set; }

    public string MissingValue { get; set; }

    public string MissingPhoto { get; set; }

    public string ReplaceValue { get; set; }

    public string ReplacePhoto { get; set; }
}