// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AviAppFinal.Server.Models;
using System;
using System.Collections.Generic;

namespace AviFinal.Api.Models
{
    public partial class Gm34bdinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Gm34blinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Gm34bsinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Gm34cainspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Gm34cbinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Gm34cfinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Gm34clinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Gm34deinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Gm34edinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Gm34elinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Gm34flinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Gm34lminspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Gm34mpinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Gm34rfinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Gm34sninspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Gm34trinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }
}
