// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AviAppFinal.Server.Models;
using System;
using System.Collections.Generic;

namespace AviFinal.Api.Models
{
    public partial class Gm35blinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Gm35bsinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Gm35cainspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Gm35cbinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Gm35cfinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Gm35clinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Gm35deinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Gm35edinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Gm35elinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Gm35flinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Gm35lminspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Gm35mpinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Gm35rfinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Gm35sninspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Gm35trinspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }

    public partial class Gm35wainspect : IInspectLocoEntity
    {
        public int Id { get; set; }

        public int LocoNumber { get; set; }

        public string LocoClass { get; set; } = null!;

        public string LocoModel { get; set; } = null!;

        public string FormId { get; set; } = null!;

        public string PartId { get; set; } = null!;

        public string PartDescr { get; set; } = null!;

        public string GoodCheck { get; set; } = null!;

        public string RefurbishCheck { get; set; } = null!;

        public string MissingCheck { get; set; } = null!;

        public string ReplaceCheck { get; set; } = null!;

        public string RefurbishValue { get; set; }

        public string MissingValue { get; set; }

        public string MissingPhoto { get; set; }

        public string ReplaceValue { get; set; }

        public string ReplacePhoto { get; set; }

        public string LaborValue { get; set; }

        public int Phase { get; set; }
    }
}
