// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AviFinal.Api.Models;

public partial class MasterLocosTE
{
    public int LocoNumber { get; set; }

    public string InventoryNumber { get; set; }

    public string LocoType { get; set; }

    public string LocoClass { get; set; }

    public string LocoModel { get; set; }

    public int Phase { get; set; }

    public string MasterList { get; set; }

    public decimal NetBookValue { get; set; }

    public decimal ScrapValue { get; set; }

    public decimal BenchmarkValue { get; set; }

    public int TareWeight { get; set; }
}