// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AviFinal.Api.Models;

public partial class MasterWagonsTFR
{
    public int WagonNumber { get; set; }

    public string WagonType { get; set; }

    public int Phase { get; set; }

    public string MasterList { get; set; }

    public string CommodityGrouping { get; set; }

    public string BrakeSystem { get; set; }

    public string MisGroup { get; set; }

    public string MisCr { get; set; }

    public string WagonGroup { get; set; }

    public decimal NetBookValue { get; set; }

    public decimal ScrapValue { get; set; }

    public decimal BenchmarkValue { get; set; }

    public int TareWeight { get; set; }
}