// <auto-generated />
using AviAppFinal.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AviFinal.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("AviAppFinal.Server.Models.LocoDashboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssessmentCert")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssessmentQuote")
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyDamage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyPhotos")
                        .HasColumnType("TEXT");

                    b.Property<string>("DateAssessed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InspectorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InspectorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocoClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocoModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LocoNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocoPhoto")
                        .HasColumnType("TEXT");

                    b.Property<string>("MissingPhotos")
                        .HasColumnType("TEXT");

                    b.Property<string>("MissingValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefurbishValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplacePhotos")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplaceValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeAssessed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LocoDashboard", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
